name: Bug report (Web - CSS - JS)
description: Report a bug which occurs in a Web Application
title: "Bug: "
labels: ["bug", "waiting for feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill up this bug report!

        There are a lot of different ways to use Font Awesome. In order to help us
        with debugging, please provide as much information as you can.

        A reduced, reproducible test case would definitely help the process.
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: What happened? What are you seeing? How did you arrive here?
    validations:
      required: true
  - type: input
    id: reproducible-test-case
    attributes:
      label: Reproducible test case
      description: Provide a URL to a reproducible use case. Use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem.
  - type: input
    id: version
    attributes:
      label: Font Awesome Version
      description: Provide the version of Font Awesome affected by this bug.
      placeholder: v5.15.0
    validations:
      required: true
  - type: dropdown
    id: serving
    attributes:
      label: Serving
      multiple: true
      options:
        - Kit
        - Font Awesome CDN
        - Self-hosted
        - Other (as specified in the bug description)
    validations:
      required: true
  - type: dropdown
    id: implementation
    attributes:
      label: Implementation
      multiple: true
      options:
        - CSS
        - SVG+JS
        - SVG Sprites
        - Other (as specified in the bug description)
    validations:
      required: true
  - type: textarea
    id: browser-operating-system
    attributes:
      label: Browser and Operating System
      description: Provide information about the browser and opeating system affected by this bug. [List of supported browsers.](https://fontawesome.com/v5.15/how-to-use/on-the-web/other-topics/browser-support) [What's my browser?](https://www.whatsmybrowser.org)
      placeholder: |
        - Chrome 94 on Windows 10
        - Firefox 92 on macOS
    validations:
      required: true
  - type: checkboxes
    id: web-bug-report-checklist
    attributes:
      label: Web bug report checklist
      options:
        - label: 'The title starts with "Bug: " and is followed by a short summary'
          required: true
        - label: 'I have included a test case because my odds go _way_ up that the team can fix this when I do'
        - label: 'I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate'
          required: true
