name: Feature request
description: Suggest an idea for Font Awesome
title: "Feature request: "
labels: ['feature']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to request a new feature!
