name: Icon request
description: Suggest an icon to be included in Font Awesome
title: "Icon request: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new icon! Please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs) to better understand how requests work.
  - type: textarea
    id: use-case
    attributes:
      label: What can it be used for?
      description: Describe how this icon could be used. If you are requesting a brand, please provide details of the brand as well as an official website.
  - type: textarea
    id: example
    attributes:
      label: Example image
      description: Insert the example image here if necessary. A good example is a single color image which plays well at small sizes (16px)
  - type: checkboxes
    id: icon-request-checklist
    attributes:
      label: Icon request checklist
      options:
        - label: 'This is a single icon or matched pair (Ex: `lock` / `unlock`)'
          required: true
        - label: 'The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)'
          required: true
        - label: I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
          required: true
        - label: The request is for a concrete object or I've included an example of what I have in mind
          required: true
