name: Bug report (Web)
description: Create a report to help us improve
title: "Bug: "
labels: ["bug", "waiting for feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill up this bug report!

        There are a lot of different ways of using Font Awesome. In order to help us
        debugging, please provide as much information as you can.

        A reduced reproducible test case would definitely help the process.
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: What happened? What are you seeing? How did you arrive here?
    validations:
      required: true
  - type: textarea
    id: reproducible-test-case
    attributes:
      label: Reproducible test case
      description: Describe any details about the test case that we need to know
      value: Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem
  - type: dropdown
    id: serving
    attributes:
      label: Serving
      multiple: true
      options:
        - Kit
        - Font Awesome CDN
        - Self-hosted
        - Other (please specify in the bug description)
    validations:
      required: true
  - type: dropdown
    id: implementation
    attributes:
      label: Implementation
      multiple: true
      options:
        - CSS
        - SVG+JS
        - SVG Sprites
        - Other (please specify in the bug description)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      description: [List of supported browsers](https://fontawesome.com/v5.15/how-to-use/on-the-web/other-topics/browser-support)
      multiple: true
      options:
        - Chrome
        - Internet Explorer
        - Firefox
        - Safari
        - Microsoft Edge
        - Opera
        - Yandex
        - Other (please specify in the bug description)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
    validations:
      required: true
  - type: checkboxes
    id: web-bug-report-checklist
    attributes:
      label: Web bug report checklist
      options:
        - label: 'I have included a test case because my odds go _way_ up that the team can fix this when I do'
        - label: 'I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate'
          required: true
